name: Integration Tests


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        accounts: ${{ secrets.ACCOUNTS }}
        account: ${{ secrets.ACCOUNT }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test
