name: Integration Tests


on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install NPM Packages
      run: npm ci

    - name: Run Integration Tests
      run: npm test
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        accounts: ${{ secrets.ACCOUNTS }}
        account: ${{ secrets.ACCOUNT }}
